# Generated by Django 4.1.5 on 2023-01-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("genre", models.CharField(max_length=32)),
                ("content", models.TextField()),
                ("director", models.CharField(max_length=32)),
                ("actor", models.CharField(max_length=32)),
                ("runningtime", models.IntegerField()),
                ("rate", models.IntegerField()),
            ],
        ),
    ]
