# Generated by Django 4.1.5 on 2023-01-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="date",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
